language: java
jdk: oraclejdk8

cache:
  directories:
  - .gradle
  - gradle
  - distCache



before_install:
- chmod +x gradlew

install: 
- ./gradlew desktop:dist
- mkdir -p dist
- mkdir -p distCache

build: true

before_deploy:
- git config --local user.name "Alexander"
- git config --local user.email "alexander@teamcorgi.com"
- git tag "$TRAVIS_BUILD_NUMBER"
- mv desktop/build/libs/desktop-1.0.jar dist/desktop.jar
- wget http://libgdx.badlogicgames.com/packr/packr.jar -P distCache
- java -jar distCache/packr.jar packr-travis.json
- zip -r build.zip dist
- ls

script: true

test: true


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $API_KEY
  file: build.zip
  on:
    branches: master
