language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1
  - distCache

before_install:
- chmod +x gradlew

install: true

script: true

build: 
- ./gradlew desktop:dist
- mkdir dist
- mkdir distCache

- mv desktop/build/libs/desktop-1.0.jar dist/desktop.jar
- wget http://libgdx.badlogicgames.com/packr/packr.jar -P /distCache
- java -jar /distCache/packr.jar packr-travis.json

test: true

before_deploy:
- zip -r build.zip dist

deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file:
  - dist.zip
  on:
    branches: master
