package works.maatwerk.generals.enums;

public enum TileStatus {
    NONE, ATTACK_AVAILABLE, ATTACK_UNAVAILABLE, HEAL_AVAILABLE, HEAL_UNAVAILABLE, MOVE_AVAILABLE, MOVE_SELECT, MOVE_UNAVAILABLE, SELECT_ALLY, SELECT_ENEMY, SELECT_HEAL
}
